# Generated by Django 3.2.9 on 2021-12-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={},
        ),
    ]
