# Generated by Django 3.2.9 on 2021-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDos', '0003_alter_todos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
