# Generated by Django 3.2.9 on 2021-12-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDos', '0008_auto_20211212_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ('order',)},
        ),
    ]
